# Exported from Render on 2024-07-12T02:49:49Z
services:
- type: web
  name: lollicupApp
  runtime: docker
  repo: https://github.com/RunningSmartCat/lolicupApp
  plan: free
  envVars:
  - key: SHOPIFY_APP_URL
    sync: false
  - key: SHOPIFY_API_SECRET
    sync: false
  - key: SHOPIFY_API_KEY
    sync: false
  - key: SCOPES
    sync: false
  - key: NODE_ENV
    sync: false
  - key: HOST
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
